APP_NAME: mini-RAG
APP_VERSION: "0.1"
FILE_ALLOWED_TYPES:
  - "text/plain"
  - "application/pdf"
FILE_MAX_SIZE: 10
FILE_DEFAULT_CHUNK_SIZE: 512000 # 512 KB
GENERATION_BACKEND: "OPENAI"
EMBEDDING_BACKEND: "OPENAI"

GENERATION_MODEL_ID: gpt-3.5-turbo-0125
EMBEDDING_MODEL_ID: embed-multilingual-light-v3.0
EMBEDDING_MODEL_SIZE: 384

DEFAULT_INPUT_MAX_TOKENS: 1024
DEFAULT_GENERATION_MAX_TOKENS: 2000
DEFAULT_GENERATION_TEMERATURE: 0.1

VECTOR_DB_BACKEND: QDRANT
VECTOR_DB_PATH: qdrant_db
VECTOR_DB_DISTANCE_METHOD: cosine
