APP_NAME: mini-RAG
APP_VERSION: "0.1"
FILE_ALLOWED_TYPES:
  - "text/plain"
  - "application/pdf"
FILE_MAX_SIZE: 10
FILE_DEFAULT_CHUNK_SIZE: 512000 # 512 KB

# ====================== LLM Config ======================
GENERATION_BACKEND: "OPENAI"
# EMBEDDING_BACKEND: "OPENAI"
EMBEDDING_BACKEND: "COHERE"

GENERATION_MODEL_ID_LITERAL:
  - gpt-4o-mini
  - gpt-4o
GENERATION_MODEL_ID: gpt-4o-mini
EMBEDDING_MODEL_ID: embed-multilingual-v3.0
# EMBEDDING_MODEL_ID: text-embedding-3-small
EMBEDDING_MODEL_SIZE: 1024
# EMBEDDING_MODEL_SIZE: 3072

DEFAULT_INPUT_MAX_TOKENS: 1024
DEFAULT_GENERATION_MAX_TOKENS: 2000
DEFAULT_GENERATION_TEMERATURE: 0.1

PRIMARY_LANGUAGE: en
DEFAULT_LANG: en

# ====================== Vector DB Config ======================
VECTOR_DB_BACKEND_LITERAL:
  - QDRANT
  - PGVECTOR
VECTOR_DB_BACKEND: PGVECTOR
VECTOR_DB_PATH: qdrant_db
VECTOR_DB_DISTANCE_METHOD: cosine
VECTOR_DB_PGVEC_INDEX_THRESHOLD: 300
